id: P000123
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: འདུལ་བའི་ལས་ཆོག་མཐོང་བས་དོན་འགྲུབ། །
  authors:
  - མཛད་པ་པོ། ཀརྨ་པ་མི་བསྐྱོད་རྡོ་རྗེ།
  layers:
  - book_title
  - author
  - chapter_title
  - tsawa
  - quotation
  - sabche
  - yigchung
  id: VVI-MD-002
web_metadata:
  title:
    en: Meaningful to Behold:The Collection of Vinaya Rituals
    bo: འདུལ་བའི་ལས་ཆོག་མཐོང་བས་དོན་འགྲུབ།
  collection:
    en: VVI Mikyo Dorje Series–  Book 2
    bo: མི་བསྐྱོད་རྡོ་རྗེ་གསུང་།–  དེབ། ༢
  author:
    en: Eighth Karmapa Mikyo Dorje
    bo: ཀརྨ་པ་སྐུ་ཕྲེང་བརྒྱད་པ་མི་བསྐྱོད་རྡོ་རྗེ།
  pusblisher:
    en: Vajra Vidya Institute
    bo: བཛྲ་བིདྱཱ་གཙུག་ལག་སློབ་གཉེར་ཁང་།
  sku: VVI-MD-002
  category:
    en: Vinaya
    bo: འདུལ་བ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: VVI-MD-002.epub
  description:
    en: ༄༅། །སྟོན་པ་བཅོམ་ལྡན་འདས་དེ་ཉིད་ཀྱིས་འདུལ་བའི་སྡེ་སྣོད་མཐའ་ཡས་པ་ཞིག་གསུངས་པ་ལས།
      བོད་གངས་ཅན་གྱི་ཁྲོད་འདིར་འཕགས་པ་གཞི་ཐམས་ཅད་ཡོད་པར་སྨྲ་བའི་འདུལ་བར་གཏོགས་པ་རྩ་བའི་ལུང་སོ་སོ་ཐར་པ་གཉིས་དང་།
      བཤད་པའི་ལུང་སྡེ་བཞི། བཤད་པ་ལས་མཐའ་དཔྱད་ཀྱི་ཆ་དང་། བྱ་བ་ལག་ལེན་གྱི་ཆོ་ག་གཉིས་ཡོད་པ་ལས།
      སློབ་དཔོན་ཡོན་ཏན་འོད་ཀྱིས་བཤད་པ་རྣམས་གོ་རིམ་དང་བཅས་ཏེ་ཕྱོགས་གཅིག་ཏུ་བསྡུས་པ་འདུལ་བ་མདོ་རྩ་བ་དང་ལག་ལེན་གྱི་ཆོ་ག་རྣམས་གཅིག་ཏུ་བསྡུས་པ་འདུལ་བ་ལས་བརྒྱ་རྩ་གཅིག་ཏུ་མཛད་པ་འདི་དག་དར་ཆེ་ཞིང་།
      ད་ལྟའི་ལས་ཆོག་ལས་དིང་སང་གི་དུས་སུ་ཉེ་བར་མཁོ་བ་ཅུང་ཟད་གཅིག་བསྡུས་ནས་བརྗོད་པ་ཡིན་ནོ།
      །
    bo: ༄༅། །སྟོན་པ་བཅོམ་ལྡན་འདས་དེ་ཉིད་ཀྱིས་འདུལ་བའི་སྡེ་སྣོད་མཐའ་ཡས་པ་ཞིག་གསུངས་པ་ལས།
      བོད་གངས་ཅན་གྱི་ཁྲོད་འདིར་འཕགས་པ་གཞི་ཐམས་ཅད་ཡོད་པར་སྨྲ་བའི་འདུལ་བར་གཏོགས་པ་རྩ་བའི་ལུང་སོ་སོ་ཐར་པ་གཉིས་དང་།
      བཤད་པའི་ལུང་སྡེ་བཞི། བཤད་པ་ལས་མཐའ་དཔྱད་ཀྱི་ཆ་དང་། བྱ་བ་ལག་ལེན་གྱི་ཆོ་ག་གཉིས་ཡོད་པ་ལས།
      སློབ་དཔོན་ཡོན་ཏན་འོད་ཀྱིས་བཤད་པ་རྣམས་གོ་རིམ་དང་བཅས་ཏེ་ཕྱོགས་གཅིག་ཏུ་བསྡུས་པ་འདུལ་བ་མདོ་རྩ་བ་དང་ལག་ལེན་གྱི་ཆོ་ག་རྣམས་གཅིག་ཏུ་བསྡུས་པ་འདུལ་བ་ལས་བརྒྱ་རྩ་གཅིག་ཏུ་མཛད་པ་འདི་དག་དར་ཆེ་ཞིང་།
      ད་ལྟའི་ལས་ཆོག་ལས་དིང་སང་གི་དུས་སུ་ཉེ་བར་མཁོ་བ་ཅུང་ཟད་གཅིག་བསྡུས་ནས་བརྗོད་པ་ཡིན་ནོ།
      །
